### PR TITLE
SM-3846

### PR DESCRIPTION
**Pull request by rahuldevgarg**

### CODE REVIEW

**Comment by naveen-egov** [comment]
Nginx configuration need to be changes as it's trying to navigate to index.hml each time pls connect with develops team

**Comment by gargrahuldev** [comment]
@naveen-egov @pradeepkumarcm-egov I have fixed nginix
In this configuration, the rewrite directive is used with a regular expression capture group to extract everything after the last occurrence of "/mgramseva" in the request URI. The captured part is then appended to the base URL "/mgramseva". This effectively removes everything before "/mgramseva" in the $uri variable.

**Comment by naveen-egov** [comment]
@rahuldevgarg  Changes look's fine, But need some changes in re-direction- when we click on link its not working but when we type the complete URL its working .
cc : @pradeepkumarcm-egov

**Comment by gargrahuldev** [comment]
@naveen-egov @pradeepkumarcm-egov ingress level changes need to be done for that.

**Review by naveen-egov — APPROVED** [review]

**Review by pradeepkumarcm-egov — APPROVED** [review]

**Pull request merged**
